[package]
name = "eko"
description = "Fast and simple scripting language for Rust"
version = "0.0.0"
authors = ["Ravern Koh <ravernkoh@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
failure = "0.1.3"
indexmap = "1.0.2"
